### ISSUE TITLE
Linux Kernel 5.4 - Supported?

### ISSUE THREAD

**Issue by jaddie** [thopiekar/rcraid-dkms#13]
Am I being dense or is there issues with using a kernel version of 5.4?
I am getting the below output when trying to use the dkms module:

`[jaddie@jad-arch-light rcraid-dkms]$ makepkg -si
==> Making package: rcraid-dkms 17.2.1-1 (Sat 25 Jan 2020 17:38:40 GMT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found raid_linux_driver_8_01_00_039_public.zip
  -> Found dkms.conf
  -> Found linux-4.15.patch
==> Validating source files with md5sums...
    raid_linux_driver_8_01_00_039_public.zip ... Passed
    dkms.conf ... Passed
    linux-4.15.patch ... Passed
==> Extracting sources...
  -> Extracting raid_linux_driver_8_01_00_039_public.zip with bsdtar
==> Starting prepare()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
patching file common_shell
patching file install_rh
patching file install_suse
patching file Makefile
patching file rc_adapter.h
patching file rc_init.c
patching file rc_mem_ops.c
patching file rc_msg.c
patching file uninstall_rh
patching file uninstall_suse
------------------------------------------------------------
- building for kernel 5.4.13-arch1-1
------------------------------------------------------------
make -C /lib/modules/5.4.13-arch1-1/build SUBDIRS=/home/jaddie/rcraid-dkms/src/rcraid-17.2.1 modules
make[1]: Entering directory '/usr/lib/modules/5.4.13-arch1-1/build'
scripts/Makefile.build:42: arch/x86/entry/syscalls/Makefile: No such file or directory
make[2]: *** No rule to make target 'arch/x86/entry/syscalls/Makefile'.  Stop.
make[1]: *** [arch/x86/Makefile:238: archheaders] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.4.13-arch1-1/build'
make: *** [Makefile:60: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
`

**Comment by thopiekar** [comment]
You are calling a command I don't know of. Is `makepkg -si` from your distro?
It also mentions something called `raid_linux_driver_8_01_00_039_public.zip`.
I neither distribute this one nor use it here in my repo.

Sounds to me like you are from a different distro where someone already maintains rcraid except of me.

**Comment by misiektw** [comment]
This is from Arch/Manjaro. Jaddie you need to change line in Makefile:

$(MAKE) -C $(KDIR) SUBDIRS=$(PWD) modules
to
$(MAKE) -C $(KDIR) M=$(PWD) SUBDIRS=$(PWD) modules

also
PLATFORM=$(shell uname -i)
to
PLATFORM=$(shell uname -m)

**Comment by jaddie** [comment]
Cheers for that! I'll keep that in mind if I ever need to use rcraid again, yeah this is coming from a project on the AUR itself, which is using this repo so that's interesting that you don't need the zip from the AMD site?

Apologies for the original issue formatting, GitHub must have been reading what I pasted as formatting :)

I solved it at the time by downgrading to an older kernel doing what I needed & then running away as AMD's onboard raid is terrible rubbish.

**Comment by misiektw** [comment]
> so that's interesting that you don't need the zip from the AMD site?

You don't because all needed files are unpacked in src directory in this repo. 

> I solved it at the time by downgrading to an older kernel doing what I needed & then running away as AMD's onboard raid is terrible rubbish.

Agree on that last part... At least support in Linux for it. Only thing I miss from Intel is IRST.

**Comment by thopiekar** [comment]
Should have read this conversation earlier. Just figured out the same as you did and it works now.

Please add a PR next time. I get too many mails per day and can't read every conversation.

**Comment by thopiekar** [comment]
PS: Are you really sure about `PLATFORM=$(shell uname -m)`? If so, please add a PR and give explanation by `uname -i` is a bad choice while referencing to some sources on the internet.

As everything works for me so far, I'm going to close this.

Thanks!
