### ISSUE TITLE
What device file does it create?

### ISSUE THREAD

**Issue by emerth** [thopiekar/rcraid-dkms#14]
Thomas - thanks for doing this, very much appreciated.

I have been able to get a pair of Samsung NVME SSDs with an ASUS Hyper M.2 V2 in an X570 board to show up as a  RAID0 under Windows, now trying for the same in Ubuntu Linux 18.04 (kernel 5.0.0-37-generic).

When I insert the rcraid module I get no errors, but partprobe and "parted -l" still see just a pair of NVME drives, no RAID device. 

Are there any steps I need to do beyond configuring the RAID in BIOS, and loading the rcraid module?

Cheers!
Eric

All I have in syslog/kern.log:

> 
> /var/log/syslog:Feb  2 22:21:49 rtx2080ti kernel: [  211.128625] <5>AMD, Inc. rcraid raid driver version 8.1.0 build_number 8.1.0-00039 built Feb 02 2020
> /var/log/syslog:Feb  2 22:21:49 rtx2080ti kernel: [  211.128627] <5>rcraid built on rtx2080ti by root on Sun Feb  2 22:20:42 MST 2020
> /var/log/syslog:Feb  2 22:21:49 rtx2080ti kernel: [  211.128628] <5>rcraid: cmd_q_depth 512, tag_q_depth 16, max_xfer 448, use_swl 0xffffffff
> /var/log/syslog:Feb  2 22:29:45 rtx2080ti kernel: [    8.128287] rcraid: loading out-of-tree module taints kernel.
> /var/log/syslog:Feb  2 22:29:45 rtx2080ti kernel: [    8.130128] rcraid: module license 'Proprietary' taints kernel.
> /var/log/syslog:Feb  2 22:29:45 rtx2080ti kernel: [    8.134390] rcraid: module verification failed: signature and/or required key missing - tainting kernel
> /var/log/syslog:Feb  2 22:29:45 rtx2080ti kernel: [    8.136980] <5>AMD, Inc. rcraid raid driver version 8.1.0 build_number 8.1.0-00039 built Feb 02 2020
> /var/log/syslog:Feb  2 22:29:45 rtx2080ti kernel: [    8.138832] <5>rcraid built on rtx2080ti by root on Sun Feb  2 22:28:09 MST 2020
> /var/log/syslog:Feb  2 22:29:45 rtx2080ti kernel: [    8.140687] <5>rcraid: cmd_q_depth 512, tag_q_depth 16, max_xfer 448, use_swl 0xffffffff
>

**Comment by emerth** [comment]
Closing this, as I had a look at closed issues and saw that NVME RAID is not really well supported.

But, thanks still! I can do something with SATA SSDs instead I think.

**Comment by petermat** [comment]
I would love to make it work, I need to drop dualboot because of incompatibility:(

**Comment by emerth** [comment]
> I would love to make it work, I need to drop dualboot because of incompatibility:(
> Is there any other way?

I'm not sure what your question is, as dual boot does not have any obvious connection to NVME AMD-RAID per se. My research and testing indicates NVME RAID via rcraid & AMD RAID does not work in Linux. Hope that helps.
