### ISSUE TITLE
I still can't find the disk after installation

### ISSUE THREAD

**Issue by oasis21** [thopiekar/rcraid-dkms#23]
Hello!
Thanks for providing the driver! But I still can't find the disk after installation.
I connected two disks to the SATA interface of the X470 motherboard and formed RAID 0, which is used to store data.
Ubuntu 20.04 beta is installed on SSD with M.2 interface.
After installing the system, I installed the driver by executing the following command:
sudo add-apt-repository ppa: thopiekar / rcraid
sudo apt-get update
sudo apt-get install rcraid-dkms

After restarting, the system still cannot find those two disks.
I hope this problem can be solved as soon as possible, thank you very much!
（Via Google Translate）

您好！
感谢提供驱动！但我在安装完成后仍然无法找到磁盘。
我在X470主板的SATA接口上接了两块磁盘，并组成了RAID0，用于存储数据。
Ubuntu 20.04 beta 则安装在了M.2接口的SSD上。
装完系统后，我通过执行下列命令安装了驱动：
sudo add-apt-repository ppa:thopiekar/rcraid
sudo apt-get update
sudo apt-get install rcraid-dkms

重启后，系统仍然找不到那两块磁盘。
可以的话希望这个问题能尽快解决，非常感谢！

**Comment by axiaobugs** [comment]
Do not reboot after finished install.you need chariot and do
sudo add-apt-repository ppa:thopiekar/rcraid
sudo apt-get update
sudo apt-get install rcraid-dkms

in you new linux system.

**Comment by oasis21** [comment]
Thank you for your help!

I am sorry that I am not very familiar with the chroot command, so I searched a lot of information, but in the end it was not successfully installed.

The following is my specific operation process:
ubuntu@ubuntu:~/Desktop$ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0         7:0    0     2G  1 loop /rofs
loop1         7:1    0  93.8M  1 loop /snap/core/8935
loop2         7:2    0    55M  1 loop /snap/core18/1705
loop3         7:3    0 240.8M  1 loop /snap/gnome-3-34-1804/24
loop4         7:4    0  48.3M  1 loop /snap/gtk-common-themes/1474
loop5         7:5    0  47.8M  1 loop /snap/snap-store/345
sda           8:0    1  28.9G  0 disk 
└─sda1        8:1    1  28.9G  0 part /cdrom
nvme0n1     259:0    0 232.9G  0 disk 
├─nvme0n1p1 259:9    0   529M  0 part 
├─nvme0n1p2 259:10   0    99M  0 part     【 EFI System 】
├─nvme0n1p3 259:11   0    16M  0 part 
├─nvme0n1p4 259:12   0    80G  0 part 
└─nvme0n1p5 259:13   0    50G  0 part 
nvme1n1     259:6    0 465.8G  0 disk 
├─nvme1n1p1 259:1    0    16M  0 part 
├─nvme1n1p2 259:2    0   200G  0 part 
├─nvme1n1p3 259:3    0   477M  0 part     【 /boot 】
├─nvme1n1p4 259:4    0   7.6G  0 part [SWAP]
└─nvme1n1p5 259:5    0  38.2G  0 part     【 / 】

ubuntu@ubuntu:~/Desktop$ sudo mount /dev/nvme1n1p5 /mnt
ubuntu@ubuntu:~/Desktop$ sudo mount /dev/nvme1n1p3 /mnt/boot
ubuntu@ubuntu:~/Desktop$ sudo mount -t proc none /mnt/proc
ubuntu@ubuntu:~/Desktop$ sudo mount -o bind /dev /mnt/dev
ubuntu@ubuntu:~/Desktop$ sudo mount -o bind /sys /mnt/sys

ubuntu@ubuntu:~/Desktop$ sudo cp /etc/resolv.conf /mnt/etc/resolv.conf

ubuntu@ubuntu:~/Desktop$ sudo chroot /mnt /bin/bash

root@ubuntu:/# sudo add-apt-repository ppa:thopiekar/rcraid
sudo apt-get update
sudo apt-get install rcraid-dkms

Then during the restart, I entered the BIOS to change the RAID mode to AHCI mode.

After entering the system, I modified /etc/default/grub and added modprobe.blacklist=ahci

Run sudo update-grub

After restarting, I changed the AHCI mode to RAID mode

After entering the system, the disk still cannot be found.

Then I found that lsmod | grep rcraid is empty, it seems that the installation is not successful.

Thanks again!

（Via Google Translate）



谢谢你提供的帮助！
很抱歉我对chroot命令不是很熟悉，因此我搜索了很多资料，但最后还是没有成功安装。
下面是我具体的操作过程：
ubuntu@ubuntu:~/Desktop$ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0         7:0    0     2G  1 loop /rofs
loop1         7:1    0  93.8M  1 loop /snap/core/8935
loop2         7:2    0    55M  1 loop /snap/core18/1705
loop3         7:3    0 240.8M  1 loop /snap/gnome-3-34-1804/24
loop4         7:4    0  48.3M  1 loop /snap/gtk-common-themes/1474
loop5         7:5    0  47.8M  1 loop /snap/snap-store/345
sda           8:0    1  28.9G  0 disk 
└─sda1        8:1    1  28.9G  0 part /cdrom
nvme0n1     259:0    0 232.9G  0 disk 
├─nvme0n1p1 259:9    0   529M  0 part 
├─nvme0n1p2 259:10   0    99M  0 part     【 EFI System 】
├─nvme0n1p3 259:11   0    16M  0 part 
├─nvme0n1p4 259:12   0    80G  0 part 
└─nvme0n1p5 259:13   0    50G  0 part 
nvme1n1     259:6    0 465.8G  0 disk 
├─nvme1n1p1 259:1    0    16M  0 part 
├─nvme1n1p2 259:2    0   200G  0 part 
├─nvme1n1p3 259:3    0   477M  0 part     【 /boot 】
├─nvme1n1p4 259:4    0   7.6G  0 part [SWAP]
└─nvme1n1p5 259:5    0  38.2G  0 part     【 / 】

ubuntu@ubuntu:~/Desktop$ sudo mount /dev/nvme1n1p5 /mnt
ubuntu@ubuntu:~/Desktop$ sudo mount /dev/nvme1n1p3 /mnt/boot
ubuntu@ubuntu:~/Desktop$ sudo mount -t proc none /mnt/proc
ubuntu@ubuntu:~/Desktop$ sudo mount -o bind /dev /mnt/dev
ubuntu@ubuntu:~/Desktop$ sudo mount -o bind /sys /mnt/sys

ubuntu@ubuntu:~/Desktop$ sudo cp /etc/resolv.conf /mnt/etc/resolv.conf

ubuntu@ubuntu:~/Desktop$ sudo chroot /mnt /bin/bash

root@ubuntu:/# sudo add-apt-repository ppa:thopiekar/rcraid
sudo apt-get update
sudo apt-get install rcraid-dkms

然后重启过程中，我进入BIOS修改RAID模式为AHCI模式。
进入系统后，我修改了/etc/default/grub，添加了modprobe.blacklist=ahci
执行 sudo update-grub
再重启，我修改AHCI模式为RAID模式

进入系统后，仍然无法找到磁盘。
然后我发现lsmod |grep rcraid 为空，似乎没有安装成功。
再次感谢你！

**Comment by ttong1013** [comment]
I have the same issue.  I am having the same configuration as @oasis21 with Ubuntu installed on M2 drive (no RAID) and two SATA data drives in RAID mode.  After going through the same steps, I can see the rcraid module is inserted by `lsmod | grep rcraid`.  However, I cannot see any RAID member by `lsblk`.  How to "discover" RAID disks after installing the `rcraid-dkms`?

**Comment by thopiekar** [comment]
@axiaobugs The point is not to reboot from live cd, but directly chroot after install and make the adjustments.
Another alternative is to disable RAID, install the OS, driver and reboot. Then enable RAIDxpress again and blacklist ahci manually when you are in the GRUB menu.
Once booted, edit /etc/default/grub, update-grub and reboot.

@ttong1013 You are missing the blacklist of ahci. If this is not done, it will take the hardware before rcraid and you end up with exactly these symptoms.

Please checkout my quickstart guide here: https://thopiekar.eu/other/amd-raidxpress/
And in the README.md of the project: https://github.com/thopiekar/rcraid-dkms#debianubuntu

Thanks!
