### ISSUE TITLE
5.3.0-46-generic 

### ISSUE THREAD

**Issue by axiaobugs** [thopiekar/rcraid-dkms#24]
when I chroot can and do the apt install dkms,it is show

Building for 5.3.0-28-generic 5.3.0-46-generic
/usr/sbin/dkms: line 2030: /dev/fd/62: no file or dir
/usr/sbin/dkms: line 1962: /dev/fd/62: no file or dir

what should I do

**Comment by thopiekar** [comment]
Looks like a chrooting mistake. Double check what you've bound to the chroot.
I chrooted several times using live cd and the driver here into my system.
There should be no issues here.
