### ISSUE TITLE
Bolton support

### ISSUE THREAD

**Issue by DunoCZ** [thopiekar/rcraid-dkms#26]
Hi, i tried to run this on Bolton chipset, but it won't work but I founded in sources that Bolton is available just unused, so any clues how to make it work?

**Comment by thopiekar** [comment]
As far as I read your chipset if from 2011...2016. I guess it is using different hardware and needs other drivers, too.
Please go back to your boards manufacturer and check the web for drivers.

If the driver here (originally only downloadable for x370 chipsets released 2017) doesn't work for you, I can't help you, too. Together with other people I only do porting to newer kernel versions here, sorry.
