### ISSUE TITLE
Windows Boot Manager missing

### ISSUE THREAD

**Issue by jbmerrill** [thopiekar/rcraid-dkms#28]
Hi,

After installing this package in Ubuntu 20.04 lts, windows boot manager no longer was in my uefi boot menu (i dual boot windows and linux) and I had to start a clean install of windows just far enough to load amd raid drivers (nvme).   Then I was able to get the boot manager back in uefi, but as soon as I boot into Ubuntu again (with rcraid-dkms installed), windows boot manager is removed from the boot menu again.  The boot manager resides on my nvme windows 10 x399 raid 0 array.

Any idea what can be done about this?  Could it have something to do with the modprobe.blacklist=ahci command?   For some reason my Ubuntu installation does not show the grub menu when i choose the 'ubuntu' boot menu option.

Let me know what additional information you may require.   

Thanks in advance

B.

**Comment by isudos** [comment]
If you installed Windows on the same array as Ubuntu I guess dual boot is impossible at all.

**Comment by thopiekar** [comment]
Not true. Got dual boot working here. If Windows is not listed, os-prober can't find it or you messed up your install by removing the EFI partition of Windows.
Nevertheless, closing this one here, since it definitely works here on my X470 build.

**Comment by jbmerrill** [comment]
Okay, thanks.  

Got this sorted out by running Linux on nvme mdraid with rcraid for accessing my amd raid drives.   Running Windows on stand alone nvme, and amd sata raid.   So, thanks again for replying and trying to help.  Really appreciate it.

Bryan

Sent from Mail for Windows 10
