### ISSUE TITLE
Module rcraid taking too long to load

### ISSUE THREAD

**Issue by zmp2000** [thopiekar/rcraid-dkms#31]
Hi, I have installed and rcraid-dkms is working, but it's taking too long to load in the boot

After enabling initicall debug I've checked that the module is taking about 4 seconds to load
Is there a reason why? Any thing else I can check?
I've tested with Kernels 5.3 and 5.4.0.40
and also 5.7.1 with the same results

```
[    4.998612] usb 4-2.4: reset SuperSpeed Gen 1 USB device number 4 using xhci_hcd
[    8.124236] initcall rcraid_init+0x0/0x1000 [rcraid] returned 0 after 4283681 usecs
[    8.783470] EXT4-fs (nvme0n1p5): mounted filesystem with ordered data mode. Opts: (null)
```

**Comment by thopiekar** [comment]
No idea why it takes so long. Maybe doing some sanity checks?
Anyway, it takes the same amount of time here and the driver works.
I'm not going to optimize or touch the driver in any way and risk losing stability.

**Comment by zmp2000** [comment]
@thopiekar Any Idea how to test Why?

> I'm not going to optimize or touch the driver in any way and risk losing stability.

But we are loosing to Microsoft Windows, My Windows 10 boots faster than Linux :(
Thant can't happen Lol!
