### ISSUE TITLE
Really slow loading

### ISSUE THREAD

**Issue by zmp2000** [thopiekar/rcraid-dkms#32]
I'm not sure why, but system is taking too long to boot. from dmesg I can see it is taking a lot of time loading RAID information:
[    1.632612] hid-generic 0003:093A:2533.0004: input,hiddev1,hidraw3: USB HID v1.11 Keyboard [Gaming Mouse] on usb-0000:02:00.0-5/input1
[   17.468006] raid6: avx2x4   gen() 25330 MB/s
[   17.516006] raid6: avx2x4   xor() 10427 MB/s
[   17.564009] raid6: avx2x2   gen() 23414 MB/s
[   17.612009] raid6: avx2x2   xor() 14924 MB/s
[   17.660008] raid6: avx2x1   gen() 18053 MB/s
[   17.708007] raid6: avx2x1   xor() 14328 MB/s
[   17.756010] raid6: sse2x4   gen() 17209 MB/s
[   17.804008] raid6: sse2x4   xor()  8784 MB/s
[   17.852009] raid6: sse2x2   gen() 16701 MB/s
[   17.900008] raid6: sse2x2   xor() 10964 MB/s
[   17.948012] raid6: sse2x1   gen()  7835 MB/s
[   17.996011] raid6: sse2x1   xor()  7982 MB/s
[   17.996011] raid6: using algorithm avx2x4 gen() 25330 MB/s
[   17.996012] raid6: .... xor() 10427 MB/s, rmw enabled
[   17.996012] raid6: using avx2x2 recovery algorithm
[   17.998038] xor: automatically using best checksumming function   avx       

It took 16 seconds to load RAID information, What is happening here?

**Comment by thopiekar** [comment]
I think this is not related to rcraid. If I'm not wrong these kernel modules give support for software raid using Linux kernel.
Anyway, as stated somewhere else. As long as there is no technical issues, but performance complaints, I'm not going to touch it.
