### ISSUE TITLE
Can't boot into Manjaro after installing rcraid

### ISSUE THREAD

**Issue by ProtoByter** [thopiekar/rcraid-dkms#33]
I installed rcraid through the git repository and then updated the mkinitcpio.conf then ran mkinitcpio - p linux58.
Now my pc shows the error:
`mount: /new_root: can't find UUID=<a long uuid>`
I get sent to an emergency shell and when I do `ls /dev` there are no sd* devices

Is this my fault?

**Comment by ProtoByter** [comment]
I had installed Manjaro onto the ssd through an 2.5" hdd caddy and then I installed rcraid-dkms, then placed it in my pc

**Comment by thopiekar** [comment]
Double check whether rcraid is really in your initramfs. On Ubuntu you have the lsinitramfs tool. There might be something similar on your distro :)

**Comment by ProtoByter** [comment]
it is, `lsinitramfs | grep rcraid` displays rcraid.ko
anyway I turned it off recently
so it doesn't matter anymore
