### ISSUE TITLE
Missing trigger to rebuild the module after dist upgrade

### ISSUE THREAD

**Issue by thopiekar** [thopiekar/rcraid-dkms#6]
Upgraded myself from Ubuntu Cosmic to Disco. For some reason, I had to build rcraid manually.

**Comment by wesleysidney** [comment]
u successfully build the rcraid? what kernel?

**Comment by thopiekar** [comment]
As far as I know all kernel versions lower or equal 5.0 are working. Don't know what the oldest kernel version is.
5.1 and newer are not working again. Some people noticed errors, but I'm still on 5.0 and I'm not interested in fixing these bugs now.

**Comment by wesleysidney** [comment]
the last time i had problem with a module in linux was somewhen like 1999 and was a modem ppp from motorola... now, after days learning this thing again i got it to work on kernel 5.2, the src of the module i take from an archlinux site, and i needed to recompile the kernel with no debug options, hard work, i probably will need to manualy build it again for new kernel versions...

**Comment by thopiekar** [comment]
Can you send me the link of the sources you downloaded? Looks like there was patchwork done on Arch to make it working on more recent kernels.

Thanks!

**Comment by wesleysidney** [comment]
this one worked for me https://aur.archlinux.org/packages/rcraid-dkms/ i am using it on kernel 5.2.8 fedora 30.
