### ISSUE TITLE
pcie nvme raid possible?

### ISSUE THREAD

**Issue by kubuntugamer** [thopiekar/rcraid-dkms#7]
i recently upgraded to a Threadripper CPU and x399 chipset motherboard(an Asrock Phantom Gaming 6). A couple of days ago i purchased 2x Samsung 970 EVO+ pcie3 nvme m.2 sticks and installed them on the motherboard's m.2 slots. i am currently booting from a single intel 760p m.2 stick installed in an asrock Ultra Quad M.2 host bus adapter(is not a raid controller) with Kubuntu 19.04 as the OS.

i have gone thru the BIOS setti gs and enabled raid mode for the sata controller and turned on nvme raid mode under amd pbs(?) section. afyer a reboot and entering the bios again i was able to initialize the nvme sticks for raid use and assemble an array.

i booted to the OS(rcraid-dkms was already installed as i used it to test with a 2x 2.5in ssd raid 0 array and it worked splendidly), however i am unable to see any raid device composed of the two nvme sticks( the previous sata ssd array was deleted and the drives removed). only the two seperate nvme devices show up in fdisk.

is the current version of rcraid able to support nvme raid mode,.and if so, where might i find some documentation on how to get this array recognized by the OS.....i have followed many guides but so far have been unsuccesful with any attempts....alot of guides suggest to boot ubuntu installer in uefi mode, but i am not having any succsss to get the installer to reach a desktop. my desire is to have a 2TB raid 0 root that is bootable. i have looked into mdadm and a bootable array is not possible via that route and I'm not a fan of lvm.

is what i am asking possible?

some further info:

last bit of dmesg output concerning rcraid module:
----------------------------------------------------------------
[  859.325295] <5>AMD, Inc. rcraid raid driver version 8.1.0 build_number 8.1.0-00039 built Jul 05 2019
[  859.325297] <5>rcraid built on kubuntu by root on Fri 05 Jul 2019 07:53:18 PM UTC
[  859.325299] <5>rcraid: cmd_q_depth 512, tag_q_depth 16, max_xfer 448, use_swl 0xffffffff
[  859.325420] <5>rcraid_probe_one: vendor = 0x1022 device 0x43bd
[  859.325429] <5>rcraid_probe_one: Total adapters matched 1
[  859.325847] <5>rcraid: rc_init_adapter 64 bit DMA enabled
[  859.326014] <6>### rc_init_adapter(): RC_EnableZPODD = 0
[  859.326096] <3>rcraid:0 request_threaded_irq irq 160
[  859.326101] <5>rcraid: card 0: AMD, Inc. AHCI
[  860.400327] <6>rcraid: rc_event: config change detected on bus 0
[  860.400867] scsi host4: AMD, Inc. AMD-RAID
[  860.406385] scsi 4:0:24:0: Processor         AMD-RAID Configuration    V1.2 PQ: 0 ANSI: 5
[  860.411387] scsi 4:0:24:0: Attached scsi generic sg3 type 3
----------------------------------------------------------------------------------------
as you can see it fails to create an sdX device, but is recognized.

listing of fdisk -l:
-------------------------------------------------------------------
Disk /dev/loop0: 1.7 GiB, 1845854208 bytes, 3605184 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/sda: 5.6 TiB, 6143996854272 bytes, 11999993856 sectors
Disk model: ARC-1231-VOL#01 
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 97E0EB8F-E0B4-4355-B889-DCDF8E6D8322

Device     Start         End     Sectors  Size Type
/dev/sda1   2048 11999991807 11999989760  5.6T Linux filesystem

Disk /dev/nvme0n1: 953.9 GiB, 1024209543168 bytes, 2000409264 sectors
Disk model: INTEL SSDPEKKW010T8                     
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: F95B1B91-01E0-4AD3-A9A5-C68E08FFCA97

Device         Start        End    Sectors   Size Type
/dev/nvme0n1p1  2048 2000408575 2000406528 953.9G Linux filesystem

Disk /dev/nvme1n1: 931.5 GiB, 1000204886016 bytes, 1953525168 sectors
Disk model: Samsung SSD 970 EVO Plus 1TB            
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x8fa8c2d5

Device         Boot Start        End    Sectors   Size Id Type
/dev/nvme1n1p1         63 1953497150 1953497088 931.5G 82 Linux swap / Solaris

Disk /dev/nvme2n1: 931.5 GiB, 1000204886016 bytes, 1953525168 sectors
Disk model: Samsung SSD 970 EVO Plus 1TB            
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x3313112f

Device         Boot Start        End    Sectors   Size Id Type
/dev/nvme2n1p1         63 1953497150 1953497088 931.5G 82 Linux swap / Solaris

Disk /dev/sdb: 7.5 GiB, 8004829184 bytes, 15634432 sectors
Disk model: USB Flash Drive 
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x4b9627aa

Device     Boot   Start     End Sectors  Size Id Type
/dev/sdb1  *          0 3742559 3742560  1.8G  0 Empty
/dev/sdb2       3711844 3719331    7488  3.7M ef EFI (FAT-12/16/32)
--------------------------------------------------------------------------------------------

this is while booted from a Kubuntu USB installer in UEFI mode. you can clearly see the nvme devices listed ( /dev/nvme1n1 and  /dev/nvme2n1, not sure what that swap partition type is about).

if you need anymore info, please let me know.

**Comment by kubuntugamer** [comment]
I'm clsoing this issue. I received a reply from the rcraid patches github owner and he pretty much stated that as of this current time, PCIE NVME RAID with the current version of the driver for AMD-RAID for Linux "may or may not be capable" as he doesn't have any NVME sticks to experiment with. Not to mention, most of the driver files are binary blobs and any source code provided is fairly minimal at best. 

perhaps at some point in the future the AMD-RAID chipset will be supported by dmraid and PCIE NVME FakeRAID will be possible.

**Comment by thopiekar** [comment]
Same here. Also have no NVME sticks installed. Only know that you need to switch into NVME mode to make them visible in AMD RaidXpress.
But yes, can't test it really as I never had some in my hands.

**Comment by vicliu624** [comment]
my x570 is inpossible  about pcie nvme raid
