### ISSUE TITLE
cant install on kernel 5.2

### ISSUE THREAD

**Issue by wesleysidney** [thopiekar/rcraid-dkms#8]
i am using fedora 30 with kernel 5.2 build with ahci as module,  when i try to instal the src patched it give me the error

>  FATAL: modpost: GPL-incompatible module rcraid.ko uses GPL-only symbol '__init_work'

**Comment by wesleysidney** [comment]
when i try to install the module i got the error, here is the log file from dkms

> DKMS make.log for rcraid-8.1.0 for kernel 5.2.6-201.raid.fc30.x86_64 (x86_64)
> qua ago  7 18:24:51 -03 2019
> ------------------------------------------------------------
> - building for kernel 5.2.6-201.raid.fc30.x86_64
> ------------------------------------------------------------
> make -C /lib/modules/5.2.6-201.raid.fc30.x86_64/build SUBDIRS=/var/lib/dkms/rcraid/8.1.0/build modules
> make[1]: Entering directory '/home/wesley/kernel/kernel-5.2.fc30/linux-5.2.6-201.raid.fc30.x86_64'
> Makefile:213: ================= WARNING ================
> Makefile:214: 'SUBDIRS' will be removed after Linux 5.3
> Makefile:215: Please use 'M=' or 'KBUILD_EXTMOD' instead
> Makefile:216: ==========================================
> ln -sf `basename /var/lib/dkms/rcraid/8.1.0/build/rcblob.x86_64.o .o` /var/lib/dkms/rcraid/8.1.0/build/rcblob.x86_64.o
>   CC [M]  /var/lib/dkms/rcraid/8.1.0/build/rc_init.o
>   CC [M]  /var/lib/dkms/rcraid/8.1.0/build/rc_mem_ops.o
>   CC [M]  /var/lib/dkms/rcraid/8.1.0/build/rc_msg.o
>   CC [M]  /var/lib/dkms/rcraid/8.1.0/build/rc_event.o
> /var/lib/dkms/rcraid/8.1.0/build/rc_init.c: In function ‘rcraid_resume_one’:
> /var/lib/dkms/rcraid/8.1.0/build/rc_init.c:1101:9: warning: ignoring return value of ‘pci_enable_device’, declared with attribute warn_unused_result [-Wunused-result]
>  1101 |         pci_enable_device(adapter->pdev);
>       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /var/lib/dkms/rcraid/8.1.0/build/rc_init.c:1126:5: warning: ignoring return value of ‘pcim_enable_device’, declared with attribute warn_unused_result [-Wunused-result]
>  1126 |     pcim_enable_device(pdev);
>       |     ^~~~~~~~~~~~~~~~~~~~~~~~
>   CC [M]  /var/lib/dkms/rcraid/8.1.0/build/rc_config.o
>   CC [M]  /var/lib/dkms/rcraid/8.1.0/build/vers.o
>   LD [M]  /var/lib/dkms/rcraid/8.1.0/build/rcraid.o
>   Building modules, stage 2.
>   MODPOST 1 modules
> FATAL: modpost: GPL-incompatible module rcraid.ko uses GPL-only symbol '__init_work'
> make[2]: *** [scripts/Makefile.modpost:91: __modpost] Error 1
> make[1]: *** [Makefile:1604: modules] Error 2
> make[1]: Leaving directory '/home/wesley/kernel/kernel-5.2.fc30/linux-5.2.6-201.raid.fc30.x86_64'
> make: *** [Makefile:60: all] Error 2
> 

may anyone help

**Comment by wesleysidney** [comment]
ok, after all the problem was my kernel, i was running a kernel with debug options, i just finished building the  new kernel with no debug and everithing is working fine.

**Comment by Herrie82** [comment]
OK, I had some initial issues with 5.1 kernels (building but not booting). I'm still on 5.0.21 here for now because of this. I guess I'll give the 5.2 kernels a try soon.

**Comment by wesleysidney** [comment]
i am able to compile only with make -i command, the install dont work, so i compile with make -i and manualy put the thing on the folder, cant use the dkms becouse i dont know how to ignore errors there...

**Comment by thopiekar** [comment]
Any news on the >= 5.1 problems?
I tried also newer kernels now, before moving to the next Ubuntu version.

Have the same issues as you have: Builds, but doesn't load.

**Comment by thopiekar** [comment]
The module works fine again with 5.3.x which is going to be used in Ubuntu Eoan.
https://github.com/thopiekar/rcraid-dkms/commit/719f12bb16ec74b6843489b62453031e10fec405

**Comment by Herrie82** [comment]
Well this fixes the 5.3 issue. But shouldn't we try to solve 5.1/5.2 too?

**Comment by thopiekar** [comment]
To be honest, I'm not interested in these kernel versions. I'm on the latest development version of Ubuntu and 5.3 will be used for this release.
If someone else needs these kernel versions running (for whatever reason), she/he can look for a solution.
Additionally, it should be not a big deal to upgrade the kernel. On Ubuntu, you can take more recent vanilla kernels, too.
